import { app } from "../firebase.js";
import { getFirestore, doc, setDoc } from "firebase/firestore";

const db = getFirestore(app);
//connectFirestoreEmulator(db, '127.0.0.1', 8080);

(async () => {
  const productsData = [
    {
      id: "0JhhzNFzNyUOL246zGi4",
      price: 3.4,
      category: "ARMA TU BANDEJA",
      name: "FALAFEL (4 UNID)",
    },
    {
      id: "0iXbhhon5Mi4z4eb3D8o",
      name: "CRISPY BREAK",
      stock: null,
      price: 8,
      category: "HAMBURGUESAS",
    },
    {
      id: "0u1bwrRKIlkQhUV6p6Y9",
      price: 5,
      name: "TINTO DE VERANO",
      category: "LICORES",
    },
    {
      id: "13j3nzaiqiwgGk8UuuNY",
      name: "EXTRA 1",
      category: "EXTRAS",
      price: 1,
    },
    {
      id: "1IJlagOtcqKlcHpItLkZ",
      ingredients: "CERVEZA SOLERA AZUL",
      name: "MICHELADA DE CERVEZA SOLERA AZUL",
      category: "LICORES",
      price: 2.5,
    },
    {
      id: "1Z6oBWZjRzgkQVaWc2NZ",
      category: "COFFEE LOVERS",
      subCategory: "TORTAS",
      price: 0.5,
      name: "BISCOTTI",
    },
    {
      id: "1wybMWlsOLk5x3PgpMMP",
      category: "COFFEE LOVERS",
      name: "MACHIATO",
      price: 2.5,
      subCategory: "EXPRESSO",
    },
    {
      id: "2XnoTC6ot5mmndYP9ErE",
      name: "REFRESCO 2LT COCA COLA",
      price: 3,
      stock: 3,
      category: "BEBIDAS",
    },
    {
      id: "2u5W3DHZk6zPOnAUBVZk",
      price: 2.5,
      category: "LICORES",
      name: "MICHELADA DE CERVEZA ZULIA",
      ingredients: "CERVEZA ZULIA",
    },
    {
      id: "3dGppi5PjuItDG6Sfco2",
      stock: null,
      name: "REFRESCOS LATA 355ML PEPSI ZERO",
      price: 2,
      category: "BEBIDAS",
    },
    {
      id: "3uns8wZSohi3Aes9M9F4",
      stock: null,
      category: "PROMOS",
      price: 15,
      name: "MATCH EXPRESS",
    },
    {
      id: "4AUSSK36I4Ujytst7JPC",
      ingredients: "CERVEZA LIGHT",
      price: 2.5,
      name: "MICHELADA DE CERVEZA LIGHT",
      category: "LICORES",
    },
    {
      id: "4HbCuy0dYNjp4ZpWOztb",
      category: "COFFEE LOVERS",
      name: "AREQUIPE",
      subCategory: "MALTEADAS",
      price: 7,
    },
    {
      id: "5WCjVcV0UvlLcMbjlSIg",
      category: "POSTRES",
      price: 3.5,
      stock: 100,
      name: "PIE DE LIMÓN",
    },
    {
      id: "6cxIxsi5Y8rbwkg9HkxI",
      category: "ARMA TU BANDEJA",
      name: "PAPAS FRITAS",
      price: 2.5,
    },
    {
      id: "6fMntdp0hbGMtn2EXpwA",
      category: "EXTRAS",
      stock: null,
      name: "PINCHO LOMITO",
      price: 4.5,
    },
    {
      id: "7ds94N8ymMrTYU3KHMzH",
      price: 20,
      category: "SMASH CRUJIENTE",
      name: "FAMILY PACK",
    },
    {
      id: "7u967kXzb8OdKn5BZvBh",
      category: "COFFEE LOVERS",
      subCategory: "TORTAS",
      price: 3,
      stock: null,
      name: "VAINILLA",
    },
    {
      id: "8ITYPsXKmbl2Vwm4TV9D",
      subtract: 10,
      ingredients: "CERVEZA SOLERA AZUL",
      price: 18,
      name: "TOBO 10 CERVEZA SOLERA AZUL",
      category: "LICORES",
    },
    {
      id: "9jcXKiBthIHyuWewOEha",
      ingredients: "SOLERA AZUL",
      category: "LICORES",
      price: 2.5,
      name: "CHELADA DE CERVEZA SOLERA AZUL",
    },
    {
      id: "9psC9S6qOFahXdDRxDFh",
      stock: null,
      category: "COFFEE LOVERS",
      name: "AMERICANO",
      subCategory: "EXPRESSO",
      price: 2,
    },
    {
      id: "9ynO81ifXVmcqBvltRGY",
      name: "DONAS",
      price: 2,
      stock: 100,
      category: "POSTRES",
    },
    {
      id: "AolqPt31OchCfLbmtcM4",
      stock: 6,
      price: 55,
      category: "LICORES",
      name: "WHISKY OLD PAR",
    },
    {
      id: "B0kbVQhZMXszHuKw6GtO",
      name: "HAMBURGUESA CLASICA ",
      price: 8,
      stock: null,
      category: "HAMBURGUESAS",
    },
    {
      id: "BMapHEF6oQtB8oPwTadS",
      category: "EXTRAS",
      name: "CEBOLLA CARAMELIZADA",
      price: 0.3,
    },
    {
      id: "Bk9ZTHs39zhzjMmW7ZOl",
      subCategory: "ICED COFFEE ",
      category: "COFFEE LOVERS",
      price: 5,
      name: "VAINILLA1",
    },
    {
      id: "BltK7RifybLpFlpEcR1O",
      category: "COFFEE LOVERS",
      price: 3.5,
      name: "WHITE",
      stock: null,
      subCategory: "FLAT",
    },
    {
      id: "BoHcCJgSViJUbojOeMcb",
      price: 5,
      category: "MENU KIDS",
      name: "NUGGETS",
      stock: null,
    },
    {
      id: "CPuwsaznYfM9bbDeraeD",
      price: 20,
      name: "SANGRIA (JARRA)",
      category: "LICORES",
    },
    {
      id: "DElx8QUGgJTaEkgMFyar",
      price: 14,
      name: "TOBO DE 10 CERVEZA NEGRA",
      subtract: 10,
      category: "LICORES",
      ingredients: "CERVEZA NEGRA",
    },
    {
      id: "E0h24vt85rhrcHlZC2QR",
      name: "PEPINILLO",
      category: "EXTRAS",
      stock: null,
      price: 0.3,
    },
    {
      id: "EHpLVb1uciRiL8PMX47Y",
      subtract: 10,
      name: "TOBO 10 CERVEZA ZULIA",
      category: "LICORES",
      price: 14,
      ingredients: "CERVEZA ZULIA",
    },
    {
      id: "ENIl0Xv04mTi96P3BHT6",
      category: "COFFEE LOVERS",
      subCategory: "EXPRESSO",
      price: 4,
      name: "MOCA NUTELLA",
    },
    {
      id: "EPTbnGtQXQId9wD3SziC",
      stock: 2,
      price: 40,
      category: "LICORES",
      name: "RON CARUPANO",
    },
    {
      id: "EiFx7y30N6F2Tuf4QDrh",
      category: "COFFEE LOVERS",
      subCategory: "MALTEADAS",
      name: "OREO",
      price: 7,
    },
    {
      id: "F0705MPsBK2vjzw2PNsb",
      stock: null,
      name: "CAPUCCINO",
      price: 3.5,
      subCategory: "EXPRESSO",
      category: "COFFEE LOVERS",
    },
    {
      id: "F4S1J5jIamWD099dJtrC",
      category: "RACIONES",
      name: "YUCA FRITA",
      price: 4,
      stock: null,
    },
    {
      id: "FEUP3fBiGJ0dUyFOOk7l",
      category: "RACIONES",
      name: "TABAQUITOS DE UVA (16UDS)",
      price: 6,
    },
    {
      id: "FWLaXPUgN66cBn1jLOX5",
      price: 2.5,
      ingredients: "CERVEZA NEGRA",
      category: "LICORES",
      name: "MICHELADA DE CERVEZA NEGRA",
    },
    {
      id: "JKWhvrkDNTIm3DsU8aSs",
      name: "ENSUEÑO",
      subCategory: "EXPRESSO",
      category: "COFFEE LOVERS",
      price: 3.5,
    },
    {
      id: "JWXTpaI2gxzYGmPYK3iD",
      name: "REFRESCO LATA 355ML CHINOTTO",
      stock: 4,
      price: 2,
      category: "BEBIDAS",
    },
    {
      id: "JaFDXXyLMkj580ABTLqk",
      stock: 26,
      price: 2,
      name: "AGUA ÉLITE 600ML",
      category: "BEBIDAS",
    },
    {
      id: "Jbk336PQqL4db1k6X9Zh",
      stock: null,
      name: "AVELLANA",
      price: 3.5,
      category: "COFFEE LOVERS",
      subCategory: "LATTE ",
    },
    {
      id: "JowKtVyNKK2UlRB3J5vB",
      name: "BANDEJA BURGER",
      price: 20,
      stock: null,
      category: "PROMOS",
    },
    {
      id: "JwZbbLtnZj7kse9OoQFJ",
      name: "AVELLANA2",
      price: 4,
      subCategory: "FLAT",
      category: "COFFEE LOVERS",
    },
    {
      id: "KLiZk63Vh4HI5yKO1IER",
      price: 4,
      subCategory: "EXPRESSO",
      category: "COFFEE LOVERS",
      name: "DULCE ENSUEÑO",
    },
    {
      id: "KSp71c9wAEnrNbTDlIAX",
      category: "COFFEE LOVERS",
      subCategory: "MALTEADAS",
      price: 7,
      name: "NUTELLA",
    },
    {
      id: "L1bSLX3edIQsfeMuHlrF",
      category: "EXTRAS",
      name: "EXTRA 0.5",
      price: 0.5,
    },
    {
      id: "L6vR27Lkz4Z7x7d5e8yo",
      name: "CUP ESPECIAL",
      price: 5,
      category: "COFFEE LOVERS",
      subCategory: "EXPRESSO",
    },
    {
      id: "LCqYlI6Ocaf9xjIynJ8h",
      stock: null,
      price: 10,
      category: "ARABIC FOOD",
      name: "PLATO MIXTO 1",
    },
    {
      id: "LYmjaNrNsrjYyOhtPArr",
      name: " VINO CASILLERO",
      price: 25,
      category: "LICORES",
      stock: 4,
    },
    {
      id: "M6UyxoH5BXYmDhrTTIC1",
      category: "COFFEE LOVERS",
      name: "AREQUIPE",
      subCategory: "FRAPUCCINO",
      price: 7,
    },
    {
      id: "MZm6Ceu7sw3UNrUgX3Rr",
      price: 6,
      stock: null,
      category: "RACIONES",
      name: "RACION DE PINCHOS",
    },
    {
      id: "Mc8RX0u0RACNzbsbq7lk",
      stock: 2,
      price: 40,
      category: "LICORES",
      name: "RON SANTA TERESA LINAJE ",
    },
    {
      id: "MkKz16YFFgoFD18IGK5w",
      ingredients: "CERVEZA LIGHT",
      name: "CHELADA DE CERVEZA LIGHT",
      price: 2.5,
      category: "LICORES",
    },
    {
      id: "MuLVtPlWCqL0o6VnyEKy",
      name: "ENSALADA CESAR (SIN POLLO)",
      category: "RACIONES",
      price: 4.5,
      stock: null,
    },
    {
      id: "N9xeAVVpjAevqCro9KOl",
      category: "COFFEE LOVERS",
      subCategory: "FRAPUCCINO",
      name: "VICTORIA",
      price: 7,
    },
    {
      id: "NeLV6PO9COdStVxbZOjm",
      name: "CHELADA DE CERVEZA NEGRA",
      ingredients: "CERVEZA NEGRA",
      category: "LICORES",
      price: 2.5,
    },
    {
      id: "Nur3Zgs8tnn4XMyEUG9P",
      name: "REFRESCO LATA 355ML FRESCOLITA",
      price: 2,
      category: "BEBIDAS",
      stock: 9,
    },
    {
      id: "OC35KEKR1qdAiuc4DR7X",
      category: "ARABIC FOOD",
      stock: null,
      name: "PLATO MIXTO 2",
      price: 10,
    },
    {
      id: "OnVPNThLlmign4k2ZVww",
      stock: 6,
      category: "BEBIDAS",
      name: "REFRESCO LATA 355ML COCA COLA",
      price: 2,
    },
    {
      id: "P14IG61eey8qSCNF5OxY",
      ingredients: "CERVEZA ZULIA",
      name: "CHELADA DE CERVEZA ZULIA",
      price: 2.5,
      category: "LICORES",
    },
    {
      id: "Pk5bKLLyfYhWm0s0G3xf",
      category: "LICORES",
      name: "TOBO 10 CERVEZA LIGHT",
      ingredients: "CERVEZA LIGHT",
      price: 14,
      subtract: 10,
    },
    {
      id: "QxTwdXsAaUBrsUXp6AtO",
      category: "COFFEE LOVERS",
      subCategory: "LATTE ",
      price: 3.5,
      name: "CARAMELO1",
    },
    {
      id: "RFOt8x39FDK2FlpMYpc7",
      category: "SMASH CRUJIENTE",
      price: 8,
      stock: null,
      name: "TENDERS DE POLLO + ENSALADA CESAR + PAPAS",
    },
    {
      id: "RIwHsav0lrSaOKEKcY46",
      category: "COFFEE LOVERS",
      name: "TRES LECHES",
      price: 6,
      subCategory: "TORTAS",
    },
    {
      id: "RSk9R3HhebyrTinf1Afs",
      price: 2,
      category: "POSTRES",
      stock: 99,
      name: "TOSTONES",
    },
    {
      id: "RuWdFcAnWaeTDt6R0r25",
      name: "REFRESCO 1LT CHINOTTO",
      category: "BEBIDAS",
      price: 2.5,
    },
    {
      id: "Rx8UN4zmkk53BEWTM2ds",
      price: 20,
      name: "BANDEJA ARABE (4 PERSONAS)",
      category: "ARABIC FOOD",
    },
    {
      id: "S1vybfy6JievYooUX1vO",
      category: "BEBIDAS",
      stock: 6,
      name: "REFRESCO 2LT CHINOTTO",
      price: 3,
    },
    {
      id: "SKUVydWg7nMUNzU2z8Si",
      stock: null,
      name: "EXTRA 3",
      category: "EXTRAS",
      price: 3,
    },
    {
      id: "SLunBo57bnq10Sm3WarU",
      price: 5,
      stock: null,
      category: "RACIONES",
      name: "TEQUEÑOS + SALSAS",
    },
    {
      id: "SROmD5ojVl890KXtgy4t",
      name: "LOVERS",
      price: 6,
      subCategory: "FRAPUCCINO",
      category: "COFFEE LOVERS",
      stock: null,
    },
    {
      id: "TnJEXqfgKk4xWwt90AXy",
      subCategory: "FRAPUCCINO",
      category: "COFFEE LOVERS",
      stock: null,
      name: "OREO",
      price: 7,
    },
    {
      id: "UdlTQciEDENvNnSra9xR",
      category: "ARABIC FOOD",
      name: "PLATO MIXTO 3",
      price: 10,
    },
    {
      id: "VKI4KOLbko1vf1nAuJjJ",
      stock: 11,
      price: 2.8,
      category: "BEBIDAS",
      name: "REFRESCO 1,5LT CHINOTTO",
    },
    {
      id: "WjvlMxe41P963RtwU3wt",
      subCategory: "LATTE ",
      price: 3.5,
      name: "VAINILLA1",
      stock: null,
      category: "COFFEE LOVERS",
    },
    {
      id: "XMUnH5AcMqsBJB2nABlK",
      name: "REFRESCO LATA PEPSI LIGHT 355ML",
      stock: 6,
      price: 2,
      category: "BEBIDAS",
    },
    {
      id: "Xq5CXBs5N6BLAql1CP3C",
      name: "REFRESCO 1 LT FRESCOLITA",
      category: "BEBIDAS",
      price: 2.5,
      stock: 6,
    },
    {
      id: "XqmtXzlnksd2CRhw2rM4",
      category: "HOT DOGS",
      price: 2,
      name: "TRADICIONAL",
      stock: null,
    },
    {
      id: "YIZ0Fa1KyUY8dDAlsLDG",
      ingredients: "CERVEZA SOLERA VERDE",
      subtract: 10,
      category: "LICORES",
      name: "TOBO 10 CERVEZA SOLERA VERDE",
      price: 18,
    },
    {
      id: "YJctHnzHxqoWwOzvBbbX",
      category: "ARMA TU BANDEJA",
      price: 2.5,
      name: "TABAQUITOS DE UVA (8 UNID)",
    },
    {
      id: "YdYfRfNvWIpFVgdLFKL2",
      category: "ARMA TU BANDEJA",
      price: 1.8,
      stock: null,
      name: "CREMAS (BERENJENA, GARBANZO, PIMENTÓN)",
    },
    {
      id: "YjbLqD0urLnxT1e4pa2e",
      stock: null,
      price: 1,
      category: "BEBIDAS",
      name: "AGUA ÉLITE 350ML",
    },
    {
      id: "YxbopzlThuwaTsFjKRAA",
      price: 6,
      name: "KIBBE FRITO (5UDS)",
      category: "RACIONES",
      stock: null,
    },
    {
      id: "ZGhzMRBBYpijqsCNSU8o",
      name: "CHEDDAR",
      price: 0.5,
      category: "EXTRAS",
    },
    {
      id: "ZZa8d5d5bFXu0EYSl8Uv",
      category: "ARMA TU BANDEJA",
      price: 1.5,
      name: "PAN ÁRABE",
    },
    {
      id: "ZakJVH2r80krkQiIaKnk",
      price: 2.5,
      name: "REFRESCO 1LT COCA COLA",
      category: "BEBIDAS",
      stock: 11,
    },
    {
      id: "ZdwOzZmQUVhHRftg6X1B",
      price: 30,
      name: "VINO TINTO ESTRUENDO",
      category: "LICORES",
      stock: 3,
    },
    {
      id: "ZomGCmof2ZS6riOJT9z9",
      stock: null,
      price: 0.7,
      name: "TOCINETA",
      category: "EXTRAS",
    },
    {
      id: "Zv90nFHmbna7tKR524o6",
      category: "PROMOS",
      name: "FAMILY PACK",
      price: 20,
    },
    {
      id: "ZvKqtcHMOmGh1UvXJKxL",
      name: "EXTRA 2",
      price: 2,
      stock: null,
      category: "EXTRAS",
    },
    {
      id: "aHtU3Q1OFcOIz0fln2PP",
      stock: null,
      price: 6,
      name: "TRAGO DE WHISKY",
      category: "LICORES",
    },
    {
      id: "amkwyP88ILd3NbmiUltM",
      price: 5,
      category: "EXTRAS",
      name: "EXTRA 5",
    },
    {
      id: "atyq1m88dIeXPEQW9WFA",
      stock: null,
      name: "BROWNIE",
      price: 2.5,
      "1ty": 100,
      category: "POSTRES",
    },
    {
      id: "b2WXYjqWcMgrU4JCQlXN",
      name: "CHELADA DE CERVEZA SOLERA VERDE",
      category: "LICORES",
      ingredients: "CERVEZA SOLERA VERDE",
      price: 2.5,
    },
    {
      id: "bdatB1PrpPNsVDB99aGd",
      price: 8,
      name: "SERVICIO DE NARGUILE",
      category: "NARGUILE",
    },
    {
      id: "cGyLxI2vfT6otAsZPxLe",
      stock: null,
      category: "LICORES",
      name: "CERVEZA SOLERA AZUL",
      price: 2,
    },
    {
      id: "ckHzMrrKoEKXBC2MewF9",
      stock: 100,
      price: 3.5,
      name: "PIE DE PARCHITA",
      category: "POSTRES",
    },
    {
      id: "dSrY7KZ3hNL4I49En87p",
      stock: "6",
      price: 60,
      name: "WHISKY BUCHAnullS",
      category: "LICORES",
    },
    {
      id: "dZqsAeU23tZGRMmAWk0h",
      name: "FRESA",
      price: 3,
      stock: 7,
      category: "BEBIDAS",
    },
    {
      id: "eIXh51nqfN4K7ODdngRi",
      stock: 100,
      price: 3.5,
      category: "POSTRES",
      name: "YOGURT",
    },
    {
      id: "eQpyUWK7pkUOyl62RN7d",
      category: "LICORES",
      name: "TRAGO DE RON ",
      price: 4,
    },
    {
      id: "eRFKk6ghEnmY0u7BqPSx",
      name: "HAMBURGESAS",
      price: 5,
      category: "MENU KIDS",
      stock: null,
    },
    {
      id: "fp5JaZ5tJrqhL0IIOVmA",
      category: "BEBIDAS",
      stock: 19,
      name: "AGUA ÉLITE 1.5L",
      price: 2.5,
    },
    {
      id: "fpoCrXTGL67DIF4bsw8S",
      category: "HAMBURGUESAS",
      name: "REBEL BACON",
      price: 8,
      stock: null,
    },
    {
      id: "gUWjuTY9qEXAZ1Pc87Tx",
      stock: null,
      name: "SALCHICHA ALEMANA",
      price: 4.7,
      category: "HOT DOGS",
    },
    {
      id: "gZYrPXiaus2S4XMhb67w",
      stock: 8,
      name: "LIMONADA",
      price: 2.5,
      category: "BEBIDAS",
    },
    {
      id: "gt924kLL11qaWTNqhztk",
      name: "TABULE",
      price: 2.5,
      category: "ARMA TU BANDEJA",
    },
    {
      id: "h6bsBijscrMaXINxfMHc",
      price: 5,
      category: "EXTRAS",
      name: "SERVICIO LIMÓN Y SAL",
    },
    {
      id: "hOvVESraxsP4gbzy79kh",
      stock: null,
      name: "GALLETAS",
      price: 2,
      category: "COFFEE LOVERS",
      subCategory: "TORTAS",
    },
    {
      id: "iDldQREaIUhVhtC3LBBk",
      subCategory: "FRAPUCCINO",
      price: 7,
      category: "COFFEE LOVERS",
      name: "NUTELLA",
    },
    {
      id: "iS4XHcw4BEk0LWjeWvJi",
      price: 8,
      stock: null,
      category: "HAMBURGUESAS",
      name: "CHICKEN DRIVE",
    },
    {
      id: "iUu4pVUiSKmzxLZdlRlN",
      price: 3,
      stock: null,
      subCategory: "LATTE ",
      category: "COFFEE LOVERS",
      name: "ORIGINAL",
    },
    {
      id: "ihPwXqb1XsE1NuTcFj35",
      price: 3,
      name: "PICOLO DOPPIO",
      category: "COFFEE LOVERS",
      subCategory: "EXPRESSO",
    },
    {
      id: "iybpvjz1VkkWe43dwTtG",
      category: "COFFEE LOVERS",
      price: 5,
      name: "ZANAHORIA",
      subCategory: "TORTAS",
    },
    {
      id: "j4UWoJHatyOrTTOWoqtz",
      name: "CHOCOLATE",
      category: "COFFEE LOVERS",
      price: 4,
      subCategory: "TORTAS",
    },
    {
      id: "jBodqYX7tNu3Kdrtf56l",
      category: "ARMA TU BANDEJA",
      price: 4,
      name: "TABAQUITOS DE REPOLLO (4 UNID)",
    },
    {
      id: "jQ9gTed0rV8trZcBkRJg",
      price: 2.5,
      category: "LICORES",
      name: "SODA LATA 355ML MINALBA",
      stock: 32,
    },
    {
      id: "lXpp6SZr7VmxAzhXG8uA",
      stock: null,
      category: "COFFEE LOVERS",
      price: 4,
      name: "VAINILLA2",
      subCategory: "FLAT",
    },
    {
      id: "lcIgsrswywhdZqf048Gz",
      price: 1.5,
      name: "CERVEZA ZULIA",
      category: "LICORES",
      stock: 94,
    },
    {
      id: "loaAQXVWdRLsl0681vBl",
      price: 4,
      category: "RACIONES",
      stock: null,
      name: "PAPAS FRITAS",
    },
    {
      id: "m52rCk02I2TkmopRnull4",
      stock: -4,
      name: "TÉ DE JAMAICA",
      category: "BEBIDAS",
      price: 3,
    },
    {
      id: "mNBUUVGPtTwhDhZ2VK64",
      price: 2.5,
      name: "MICHELADA DE CERVEZA SOLERA VERDE",
      ingredients: "CERVEZA SOLERA VERDE",
      category: "LICORES",
    },
    {
      id: "ph6Jakf39PsPPNCupGLM",
      price: 4.8,
      name: "CREMAS DE BERENJENA, GARBANZO Y PIMENTON",
      category: "RACIONES",
      stock: null,
    },
    {
      id: "phI1gHAKVDnymPJtfCM5",
      category: "RACIONES",
      price: 6,
      name: "TABAQUITOS DE REPOLLO (8UDS)",
    },
    {
      id: "pmxN5eZU8jutH5uXfaGs",
      stock: null,
      name: "PINCHO POLLO",
      price: 3,
      category: "EXTRAS",
    },
    {
      id: "pqOEkAPLJ54fRcn8Hngs",
      name: "CARAMELO2",
      price: 4,
      category: "COFFEE LOVERS",
      subCategory: "FLAT",
    },
    {
      id: "qqVMKYSbbSQdICWvUGww",
      price: 1.5,
      name: "CERVEZA NEGRA",
      category: "LICORES",
      stock: 9,
    },
    {
      id: "r1nPXIjhwoHxQ40WC6NO",
      subCategory: "EXPRESSO",
      name: "MOCACCINO",
      price: 3.5,
      category: "COFFEE LOVERS",
    },
    {
      id: "rTOxB6ROXKAmrpgVrXTV",
      category: "LICORES",
      name: "CERVEZA SOLERA VERDE",
      stock: -1,
      price: 2,
    },
    {
      id: "rxtWVEKO5BSwGwZB2OkG",
      name: "DESCORCHE WHISKY",
      category: "LICORES",
      price: 20,
    },
    {
      id: "rz5GHix20vsq6cd1TtW6",
      stock: null,
      price: 2.5,
      name: "PICOLO",
      category: "COFFEE LOVERS",
      subCategory: "EXPRESSO",
    },
    {
      id: "tOzbVmxPdJjhHKyfqswt",
      price: 4,
      name: "KIBBE (4 UNID)",
      category: "ARMA TU BANDEJA",
    },
    {
      id: "tYALx8kSPadA7QZD2uAV",
      price: 4.7,
      category: "HOT DOGS",
      name: "CHISTORRA",
    },
    {
      id: "toPFtG2HbpFH77C3is0T",
      price: 5,
      subCategory: "ICED COFFEE ",
      name: "CARAMELO1",
      category: "COFFEE LOVERS",
    },
    {
      id: "uShULwi9u5zoOboUztQd",
      category: "LICORES",
      price: 15,
      name: "DESCORCHE RON",
    },
    {
      id: "ucN44M8syPRtD3tQMDil",
      stock: null,
      name: "SALCHICHA POLACA",
      category: "HOT DOGS",
      price: 4.7,
    },
    {
      id: "ul3Bxt49ZyCe1cHpjZEE",
      price: 6,
      name: "REFRESCO LATA PEPSI 355ML",
      category: "BEBIDAS",
    },
    {
      id: "vQWEXSe1W1Gl2WSXJ6iB",
      price: 2.5,
      name: "REFRESCO 1LT FANTA NARANJA",
      stock: 12,
      category: "BEBIDAS",
    },
    {
      id: "vSuYHzCYiTAvFCQt3aoT",
      name: "POLLO FULL SET",
      category: "SMASH CRUJIENTE",
      price: 8,
    },
    {
      id: "vgqtJxjur9MTh9SdVbip",
      name: "TENDERS DE POLLO",
      price: 5,
      stock: null,
      category: "MENU KIDS",
    },
    {
      id: "x2ebHZ3dQHNISwXL3GBv",
      category: "COFFEE LOVERS",
      subCategory: "ICED COFFEE ",
      name: "AVELLANA",
      price: 5,
    },
    {
      id: "xBQaFs5huM7YtsDtzPhM",
      stock: 15,
      price: 2.5,
      category: "BEBIDAS",
      name: "PAPELÓN CON LIMÓN",
    },
    {
      id: "xXJSMn1KwI2bjKXf8tKl",
      name: "CERVEZA LIGHT",
      stock: 117,
      category: "LICORES",
      price: 1.5,
    },
    {
      id: "xkw2Vv6NvbDHkBOpxq5j",
      stock: 2,
      price: 3,
      name: "REFRESCO 2LT 7UP",
      category: "BEBIDAS",
    },
    {
      id: "y49VdprcOpTq6xiFY91Y",
      name: "EXTRA 4",
      category: "EXTRAS",
      price: 4,
    },
    {
      id: "yaX44Ie2t3kJYi1sD26T",
      name: "TABULE",
      category: "RACIONES",
      stock: null,
      price: 6,
    },
    {
      id: "yxNolczqUlwteuNzpOSc",
      category: "POSTRES",
      name: "TRES LECHES",
      price: 3.5,
      stock: 100,
    },
  ];

  await Promise.all(
    productsData.map(async (product) => {
      const docRef = doc(db, "products", product.id);
      const { id, ...rest } = product;
      await setDoc(docRef, rest);
      console.log("Producto creado:", product.id);
    })
  );
})();
